### ISSUE TITLE
createdAt/updatedAt as default schema/model fields

### ISSUE THREAD

**Issue by nwinch** [Prismatik/dendritic#197]
What are everyone's thoughts about including `createdAt/updatedAt` as defaults for all models?  I wonder if it would be worthwhile to run with this as opt out, instead of opt in.  So far on Hosportal and Shortlyster we've needed these two timestamps for quite a few models.

Here are some pros and cons I can see.

**Pros**
- It feels like standard functionality that should at least have some footprint in Dendritic core - to what degree is up for discussion.  It's always helpful information that often you need for documents.
- Won't need to re-add for each project.

**Cons**
- It could be superfluous data for some models that don't need it.
- Might be possible bloat to super small schemas/models?  Not sure if that's a huge concern.

**Comment by kaievns** [comment]
hey mate, that's a definitely interesting idea, there is definitely a need for createdAt/updatedAt automatic tracking fearture.

but, i'm against making it a default behavior. ruby on rails had been over this problem for ages and the consensus was always to leave it as the opt in approach. basically the reasoning that implicit data structure definitions are better as they have the least surprise factor. you need to look at a data structure and see _all_ its extent. magic things like that keep people shooting themselves in the foot all the time.

but, i hear you, we need an easy setup for this feature as it is needed very often. so i see two options here that implicit, but yet simple enough.
1. make `createModel` to look if the model schema has `createdAt`/`updatedAt` properties and then setup automatic update of those for you. this way you just add them into a schema and everything will be taken care for you, kind of like we do with `rev` property.
2. add an option to `createModel`, something like `createModel(schema, { timestamps: true })`, then it will aumotaically add the `createdAt`, `updatedAt` fields to the schema and things from the option 1.

i personally like option 1 quite a bit better than option 2 for two reasons. firstly, it makes the data structure implicit and visible in the schema. and secondly, it is consistent with how the `rev` feature works at the moment.

what do you think?

**Comment by nwinch** [comment]
Yeah I like option 1 - I actually implemented that in Shortlyster.
https://github.com/Prismatik/shortlyster/blob/c27a19abf9a113b7715e86c93b2a0c16e8bd5ddb/api/src/utils/controller.js
https://github.com/Prismatik/shortlyster/blob/c27a19abf9a113b7715e86c93b2a0c16e8bd5ddb/api/src/utils/model.js

In `/utils/model` I've added the schema to the model, which is then used within the base controller to check if `createdAt/updatedAt` fields exist on `create` and `update`.

**Comment by nwinch** [comment]
Would be great to port that back in to Dendritic core, if this is the agreed approach.

**Comment by davidbanham** [comment]
It should definitely be an option in the generator. I lean towards opt out but what Nikolay says about the rails experience makes sense, so I'm happy to go with opt in.

**Comment by kaievns** [comment]
fair dinkum mates, i've added a ticket to `generator-dendritic` and making it a task https://github.com/Prismatik/generator-dendritic/issues/7

**Comment by kaievns** [comment]
on a second thought, now that dave mentioned the yeoman generator, i think we can have both.

we can make the resource generator to generate explicit `createdAt`, `updatedAt` props in the schema by default and then have a `--no-timestamps` flag for the yeoman CLI to disable those

**Comment by nwinch** [comment]
Ohh that's fancy!
