### ISSUE TITLE
Base Controller .update uses this.find which can be overwritten.

### ISSUE THREAD

**Issue by s-taylor** [Prismatik/dendritic#198]
In the base controller, the update method uses `this.find`. This is OK until you overwrite the find method of the base controller (i.e. to add permission checks). This then means the base controller update method now uses the overwritten find method and not the base controller's find method.

I don't think you can use `super.find` in this instance? Since you're not referring to the object that you're inheriting from, you just want the find method prior to it being overwritten. 

The simplest fix is just to swap it out for `Model.get`, there's no logic in the base controller find method anyway. It's probably better not to have any interdependence between the base controller methods as well?

https://github.com/Prismatik/dendritic/blob/master/resource/src/utils/controller.mustache#L42

**Comment by kaievns** [comment]
valid point, and it could be handled by saving the original base controller in a var and export a wrapped object instead, like `Object.assign({}, baseController, { extra methods })`;

but i think the problem you're having is that you're adding a permissions system inside of the RESTful controller. it's is not the REST controller job to handle permissions. REST controller should be all about CRUD operations on a model. the permissions system should live outside of it. either in the routing/middleware layer, or, if it's too complex for that, it should be an extra layer between the routing and REST controllers.

think about it this way. you have a monolith at the moment with the access control logic baked on the inside. you need to build this access control in such a way that we could later extract it in a separate proxy service that will sit between the REST API service and the public gateway.

restful controllers should do their job as usual, it should be an external to them entity that knows about users and roles, and decides whether to call a controller to find/save data or not

does it make sense?

**Comment by s-taylor** [comment]
I think you're right that ideally it would be nice to not intermingle the controller and permissions and have a separate layer to handle permissions, but we're then talking about a 4th layer routes => permissions => controller => model. If this is our ideal approach then I think that should be integrated into dendritic itself as part of the generator and make the auth object available in the permissions layer. Or at the very least make it optional to generate the permissions layer.

I don't think putting permissions into middleware or routes is the right approach as it generally is too complex as you say, but also because that means to test your permissions you then need to send http requests (if it's in the routes for example), it's much neater to just pass an authorization object (object with the users permissions) into a function to test it, since this doesn't actually need the auth service to perform the test.

In any case I think we should make the change you proposed so that it calls the base controllers version of the find method within update. I don't think you'd want your custom business logic to apply to the find used within an update? It's possible you might just trying to think it through...

**Comment by kaievns** [comment]
yup, you're absolutely right. and the plan is to build the authorisation layer as part of the dendritic infrastructure. we didn't put this as a part of the default dendritic generator for a few reasons though. firstly we didn't fully understand how we want to handle authorisation. and secondly we don't want to tailor dendritic API into monolith prone architecture, in fact we want to move away from this towards a more micro-services friendly environment.

but, regardless of the dendritic plans, building authorisation as a separate layer is the right approach. i understand that it is a bit more complicated than baking it into the controllers, but it will separate the concerns and keep the application in a refactorable state.

**Comment by kaievns** [comment]
i think we've reached a consensus here, so i'm closing this
